language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn build # npm run docs:build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  cleanup: true
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # repo: itdocsmg/itdocsmg.github.io
  keep_history: true
  target_branch: master
  on:
    branch: master
